In [18]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


### 1)create one dimensional Array

In [19]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

### 2)create Two dimensional Array

In [20]:
b=np.array([[1,2,3],[3,4,5]])


### 3)get the dimensions

In [21]:
print("dimensions of a",a.ndim)
print("dimensions of b",b.ndim)

dimensions of a 1
dimensions of b 2


### 4)get the shape . get the number of rows and columns

In [22]:
print("shape of a",a.shape)
print("shape of b",b.shape)

shape of a (3,)
shape of b (2, 3)


### 5)get the specified element of particular row particular columns

In [23]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c[1,6])

14


In [24]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


### 6)get a specified row

In [25]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

### 7)get a specified column

In [26]:
c[:,3]

array([ 4, 11])

### 8)convert array into data frame and save it as csv file

In [15]:
import pandas as pd
c=pd.DataFrame(c)
c.to_csv("array.csv")

In [16]:
c

0  1   2   3   4   5   6
0  1  2   3   4   5   6   7
1  8  9  10  11  12  13  14

### 9)get only even values in specified row

In [28]:
c[0,0:6:2]

array([1, 3, 5])

### 10)3-d example

In [31]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 11)get specified element in 3-d example

In [34]:
print(d[0,0,1])

2


### 12)replace elements in 3d array

In [36]:
d[:,1,:]=[[7,4],[3,6]]
d

array([[[1, 2],
        [7, 4]],

       [[5, 6],
        [3, 6]]])

### 13)Initialise two rows three columns of zeros matrix

In [37]:
e=np.zeros((2,3))
e

array([[0., 0., 0.],
       [0., 0., 0.]])

### 14)Initialise 3d array of4 , 3 rows 2 columns all zeros

In [39]:
f=np.zeros((4,3,3,2))
f

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

### 15)all ones matrix 3 d 4, 3 rows ,2 columns, all ones

In [41]:
g=np.ones((4,3,3,2))
g

array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]])

### 16)fill all the values with 100,3  3 rows 2 columns

In [45]:
h=np.full((3,3,2),100,dtype="float32") 
h


array([[[100., 100.],
        [100., 100.],
        [100., 100.]],

       [[100., 100.],
        [100., 100.],
        [100., 100.]],

       [[100., 100.],
        [100., 100.],
        [100., 100.]]], dtype=float32)

### 17)initialise all values with 10 as like f array

In [49]:
i=np.full_like(f,10)
i

array([[[[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]]],


       [[[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]]],


       [[[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]]],


       [[[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]],

        [[10., 10.],
         [10., 10.],
         [10., 10.]]]])

### 18)INITIALISE RANDOM 4,4 MATRIX WITH RANDOM VALUES

In [51]:
J=np.random.rand(4,4)
J

array([[5.37178000e-01, 4.03700540e-01, 9.82659817e-02, 3.92879155e-01],
       [6.32341062e-01, 6.15875656e-01, 7.28900752e-01, 7.25624012e-01],
       [5.30285414e-01, 3.71009700e-01, 4.36569125e-02, 6.62022643e-01],
       [7.76154252e-01, 1.63877599e-01, 2.25900600e-04, 3.98292135e-01]])

### 19)random 4,4 matrix with integer random values btw 4,7

In [58]:
k=np.random.randint(4,7,size=[3,3])
k


array([[6, 4, 6],
       [4, 6, 4],
       [4, 4, 6]])

### 20)generate identity matrix of 5,5

In [59]:
l=np.identity(5)
l

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 21)generate matrix of 123,123,123 without using 2d array

In [66]:
m=np.array([[1,2,3]])
n=np.repeat(m,3,axis=0)
n

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### 22)print matrix with middle value different and rows touching all different

In [70]:
o=np.ones((5,5))
print(o)
p=np.zeros((3,3))
print(p)
p[1,1]=9
print(p)
o[1:4,1:4]=p
print(o)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 23)add 2 to every element of array multiply by 2 and subract by 2 divided by 2

In [74]:
a=np.array([1,2,3,4])
b=a+2
c=a-2
d=a*2
e=a/2
print(b)
print(c)
print(d)
print(e)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


### 24)addition of two arrays

In [81]:
a=np.array([[1,2,3,4],[1,2,3,4]])

print(a+b)


[[ 6  8 10 12]
 [ 6  8 10 12]]


### 25)sin of values

In [78]:
c=np.sin(a)
print(c)
d=np.cos(a)
print(d)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


### 26) matrix multiply

In [83]:
d=np.full((3,4),2)
print(d)
e=np.full((4,3),2)
print(e)
f=np.matmul(d,e)
print(f)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
[[16 16 16]
 [16 16 16]
 [16 16 16]]


### 27)find the determinant

In [86]:
g=np.identity(3)
h=np.linalg.det(g)
print(h)

1.0


### 28)get the eigen values

In [88]:
i=np.identity(3)
print(np.linalg.eig(i))

EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


### 29)trace of a matrix

In [89]:
print(np.linalg.trace(i))

3.0


### 30)max ele  and min ele of matrix

In [93]:
a=np.array([[1,2,3],[4,5,6]])
print(np.min(a))
print(np.max(a))

1
6


### 31)get max col

In [95]:
print(np.max(a,axis=1))

[3 6]


### 32)reshape of arrays

In [96]:
print(a.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
